blank_issues_enabled: false
contact_links:
  - name: 💬 General discussion
    url: https://github.com/MoRa2297/finance-mobile/discussions
    about: For questions, unstructured ideas, or brainstorming use Discussions
