import { Color, CategoryIcon } from '@/types';

export const COLORS: Color[] = [
  { id: 1, hexCode: '#5d4c86' },
  { id: 2, hexCode: '#946aa2' },
  { id: 3, hexCode: '#c3a5b4' },
  { id: 4, hexCode: '#edeff3' },
  { id: 5, hexCode: '#d30b94' },
  { id: 6, hexCode: '#f07cab' },
  { id: 7, hexCode: '#772b9d' },
  { id: 8, hexCode: '#b732cc' },
  { id: 9, hexCode: '#2f2aa0' },
  { id: 10, hexCode: '#f47a22' },
  { id: 11, hexCode: '#ffc413' },
  { id: 12, hexCode: '#632819' },
  { id: 13, hexCode: '#96341c' },
  { id: 14, hexCode: '#c56133' },
  { id: 15, hexCode: '#e68f66' },
  { id: 16, hexCode: '#ffcba5' },
  { id: 17, hexCode: '#991919' },
  { id: 18, hexCode: '#f22020' },
  { id: 19, hexCode: '#3750db' },
  { id: 20, hexCode: '#277da7' },
  { id: 21, hexCode: '#37294f' },
  { id: 22, hexCode: '#3998f5' },
  { id: 23, hexCode: '#29bdab' },
  { id: 24, hexCode: '#235b54' },
  { id: 25, hexCode: '#8ad8e8' },
  { id: 26, hexCode: '#228c68' },
  { id: 27, hexCode: '#0ec434' },
  { id: 28, hexCode: '#7dfc00' },
  { id: 29, hexCode: '#fcff5d' },
  { id: 30, hexCode: '#ffffff' },
  { id: 31, hexCode: '#000000' },
];

export const CATEGORY_ICONS: CategoryIcon[] = [
  // { id: 1, iconName: 'cart-outline' },
  // { id: 2, iconName: 'car-outline' },
  // { id: 3, iconName: 'film-outline' },
  // { id: 4, iconName: 'medical-outline' },
  // { id: 5, iconName: 'cash-outline' },
  // { id: 6, iconName: 'flash-outline' },
  // { id: 7, iconName: 'bag-outline' },
  // { id: 8, iconName: 'restaurant-outline' },
  // { id: 9, iconName: 'home-outline' },
  // { id: 10, iconName: 'airplane-outline' },
  // { id: 11, iconName: 'gift-outline' },
  // { id: 12, iconName: 'school-outline' },
  // { id: 13, iconName: 'fitness-outline' },
  // { id: 14, iconName: 'paw-outline' },
  // { id: 15, iconName: 'game-controller-outline' },
  // { id: 16, iconName: 'musical-notes-outline' },
  // { id: 17, iconName: 'book-outline' },
  // { id: 18, iconName: 'cafe-outline' },
  // { id: 19, iconName: 'beer-outline' },
  // { id: 20, iconName: 'heart-outline' },
  // { id: 21, iconName: 'star-outline' },
  // { id: 22, iconName: 'wallet-outline' },
  // { id: 23, iconName: 'card-outline' },
  // { id: 24, iconName: 'briefcase-outline' },
];
