import { useMutation, useQueryClient } from '@tanstack/react-query';
import recurringService, {
  UpdateRecurringRulePayload,
} from '@/services/recurring.service';
import { recurringKeys } from './recurring.keys';
import { transactionKeys } from '@/stores/transaction/transaction.keys';

export const useUpdateRecurringRule = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: recurringKeys.mutations.update(),
    mutationFn: ({
      id,
      payload,
    }: {
      id: number;
      payload: UpdateRecurringRulePayload;
    }) => recurringService.updateRecurringRule(id, payload),
    onSuccess: () => {
      // Invalidate transactions — future ones will be regenerated by cron
      queryClient.invalidateQueries({ queryKey: transactionKeys.lists() });
    },
  });
};
